"""Core operation logic for INI Tools addon.

This module orchestrates the main operations (GENERATE, UPDATE).
Bridges scene analysis, INI processing, and XXMI utilities.
"""

import bpy
import os
import shutil
from typing import Dict, List
from .config import CONTAINERS_COLLECTION, ACTIVE_VARIABLE
from .scene_analysis import collect_scene_variables, build_key_sections
from .ini_processing import (
    parse_draw_lines,
    merge_draw_lines_into_content,
    collect_blend_draw_values,
    update_override_vertex_counts,
)
from .xxmi_utils import transform_xxmi_to_conditionals


def extract_filenames_from_ini(ini_filepath: str) -> List[str]:
    """Extract all .buf and .ib filenames referenced in INI Resource sections."""
    filenames = []
    with open(ini_filepath, 'r', encoding='utf-8', errors='replace') as f:
        for line in f:
            stripped = line.strip().lower()
            if stripped.startswith('filename ='):
                # Extract: "filename = HuTaoCherryPosition.buf" → "HuTaoCherryPosition.buf"
                filename = line.split('=', 1)[1].strip()
                if filename.endswith(('.buf', '.ib')):
                    filenames.append(filename)
    return filenames


def copy_extra_files(ini_filepath: str, report_func) -> None:
    """
    Copy buffer and index files from XXMI export to working folder.

    Uses INI-driven approach: parses INI for filename= references.
    Auto-detect selective: if target has .buf/.ib files, only refresh those.
    """
    scene = bpy.context.scene
    xxmi_path = getattr(scene, "xxmi", None)
    if not xxmi_path or not hasattr(xxmi_path, "destination_path"):
        report_func({'WARNING'}, "No XXMI destination path found. Skipping file copy.")
        return

    source_folder = bpy.path.abspath(xxmi_path.destination_path)
    if not os.path.isdir(source_folder):
        report_func({'WARNING'}, f"Source folder does not exist: {source_folder}")
        return

    target_folder = os.path.dirname(ini_filepath)
    if not os.path.isdir(target_folder):
        report_func({'WARNING'}, f"Target folder does not exist: {target_folder}")
        return

    # Get all files referenced in the INI
    required_files = extract_filenames_from_ini(ini_filepath)
    if not required_files:
        report_func({'INFO'}, "No .buf/.ib files found in INI. Skipping file copy.")
        return

    # Auto-detect selective mode: check if target already has .buf/.ib files
    existing_bufib = {f for f in os.listdir(target_folder)
                      if f.endswith(('.buf', '.ib'))}

    if existing_bufib:
        # Selective mode: only copy files that already exist in target
        files_to_copy = [f for f in required_files if f in existing_bufib]
        if not files_to_copy:
            report_func({'INFO'}, "No matching files to update in target folder.")
            return
    else:
        # Full mode: copy all required files
        files_to_copy = required_files

    # Copy files
    copied = 0
    for filename in files_to_copy:
        src = os.path.join(source_folder, filename)
        dst = os.path.join(target_folder, filename)
        if os.path.isfile(src):
            try:
                shutil.copy2(src, dst)
                copied += 1
            except Exception as e:
                report_func({'WARNING'}, f"Failed copying {filename}: {e}")
        else:
            report_func({'INFO'}, f"File not found in export: {filename}")

    mode_desc = "selectively updated" if existing_bufib else "copied"
    report_func({'INFO'}, f"Finished: {copied} files {mode_desc}.")


def execute_generate_mode(ini_filepath, ini_content, component_variables, report_func):
    """
    Execute GENERATE mode operation using XXMI approach.
    
    Args:
        ini_filepath: Path to INI file
        ini_content: Current INI file content (list of lines)
        component_variables: Component structure from scene analysis
        report_func: Blender report function
        
    Returns:
        Operation result dict with updated content
    """
    # Check if already generated by INI Tools (not just XXMI basic constants)
    # Look for INI Tools-specific patterns: "global persist $" variables
    ini_tools_generated = False
    for i, line in enumerate(ini_content):
        stripped = line.strip()
        # Check for "global persist $" variables (INI Tools pattern)
        if stripped.startswith('global persist $'):
            ini_tools_generated = True
            break
        # Also check for the clean Variables comment header (new format)
        if stripped == "; Variables" and i > 0 and "=======" in ini_content[i-1]:
            ini_tools_generated = True
            break
    
    if ini_tools_generated:
        report_func({'ERROR'}, "This INI already contains INI Tools toggle variables. Use 'Update Existing INI' instead of Generate.")
        return {'CANCELLED'}
    
    # Get toggle variables from scene
    try:
        toggle_variables, index_mappings, _ = collect_scene_variables()
    except RuntimeError as exc:
        report_func({'ERROR'}, str(exc))
        return {'CANCELLED'}
    
    # Build key sections
    prefs = bpy.context.preferences.addons[__package__.split('.')[0]].preferences
    keys_list = [k.strip() for k in prefs.custom_keys.split(",") if k.strip()]
    
    constants_section, present_section, key_swap_sections = build_key_sections(
        toggle_variables, keys_list, report_func
    )
    
    # Find insertion points
    constants_comment_index = None
    constants_section_index = None
    present_section_index = None
    
    for i, line in enumerate(ini_content):
        if line.strip().startswith("; Constants"):
            constants_comment_index = i
        elif line.strip() == "[Constants]":
            constants_section_index = i
        elif line.strip() == "[Present]":
            present_section_index = i
    
    if constants_section_index is not None:
        # Alice.ini style: [Constants] section exists
        # Insert after existing constants
        insert_pos = constants_section_index + 1
        while insert_pos < len(ini_content):
            line = ini_content[insert_pos].strip()
            if line.startswith('[') or (line.startswith(';') and '---' in line):
                break
            insert_pos += 1
        
        # Use build_key_sections output but skip the header since [Constants] exists
        our_content = ["\n"] + constants_section  # Keep the full clean constants section
        
        # Only add Present section if it doesn't already exist
        if present_section_index is None:
            our_content.extend(present_section)
            
        our_content.extend(key_swap_sections)
        
        ini_content = ini_content[:insert_pos] + our_content + ini_content[insert_pos:]
        
    elif constants_comment_index is not None:
        # Yuzuha.ini style: "; Constants" comment but no [Constants] section
        insert_pos = constants_comment_index + 1
        while insert_pos < len(ini_content) and ini_content[insert_pos].strip() == "":
            insert_pos += 1
        
        # Add [Constants] header + global $active + our clean content
        full_content = ["\n[Constants]\n", f"global {ACTIVE_VARIABLE} = 0\n", "\n"] + constants_section
        
        # Only add Present section if it doesn't already exist
        if present_section_index is None:
            full_content.extend(present_section)
            
        full_content.extend(key_swap_sections)
        
        ini_content = ini_content[:insert_pos] + full_content + ini_content[insert_pos:]
        
    else:
        # No Constants section at all - add everything at top
        full_constants = ["\n[Constants]\n", f"global {ACTIVE_VARIABLE} = 0\n", "\n"] + constants_section
        
        # Only add Present section if it doesn't already exist
        if present_section_index is None:
            full_constants.extend(present_section)
            
        ini_content = full_constants + key_swap_sections + ini_content
    
    # Transform to XXMI conditionals
    ini_content = transform_xxmi_to_conditionals(ini_content, component_variables, report_func)
    
    # Write result
    with open(ini_filepath, 'w', encoding='utf-8') as f:
        f.writelines(ini_content)
    
    report_func({'INFO'}, "INI file processed successfully.")
    return {'FINISHED'}


def execute_update_mode(ini_filepath, ini_content, component_variables, report_func):
    """
    Execute UPDATE mode operation using XXMI approach.
    
    Args:
        ini_filepath: Path to INI file
        ini_content: Current INI file content (list of lines)
        component_variables: Component structure from scene analysis
        report_func: Blender report function
        
    Returns:
        Operation result dict
    """
    # Check if file has INI Tools toggle variables (required for UPDATE)
    has_ini_tools_variables = False
    for line in ini_content:
        stripped = line.strip()
        if stripped.startswith('global persist $'):
            has_ini_tools_variables = True
            break
    
    if not has_ini_tools_variables:
        report_func({'ERROR'}, "This file doesn't have INI Tools toggle variables yet. Use 'Generate New INI' first to create the toggle system, then use 'Update Existing INI' to update drawindexed values.")
        return {'CANCELLED'}
    
    scene = bpy.context.scene
    
    # Get XXMI exported data
    destination_path = getattr(scene, "xxmi", None)
    if not destination_path or not hasattr(destination_path, "destination_path"):
        report_func({'ERROR'}, "No XXMI destination path found. Cannot update without XXMI export.")
        return {'CANCELLED'}
    
    destination_path = destination_path.destination_path
    if not destination_path or not os.path.isdir(destination_path):
        report_func({'ERROR'}, "Invalid XXMI destination path. Cannot update without XXMI export.")
        return {'CANCELLED'}
    
    # Find XXMI exported INI file
    exported_ini_file = None
    for filename in os.listdir(destination_path):
        if filename.lower().endswith(".ini"):
            exported_ini_file = os.path.join(destination_path, filename)
            break
    
    if not exported_ini_file or not os.path.isfile(exported_ini_file):
        report_func({'ERROR'}, "No .ini file found in XXMI destination path. Cannot update without XXMI export.")
        return {'CANCELLED'}
    
    # Parse XXMI exported INI to get mesh_name → drawindexed_value map
    with open(exported_ini_file, "r", encoding="utf-8", errors="replace") as ef:
        exported_lines = ef.readlines()
    
    from .xxmi_utils import parse_static_drawindexed, extract_mesh_name_from_comment
    static_draws = parse_static_drawindexed(exported_lines, report_func)
    
    # Build mesh_name → drawindexed_value map from XXMI data
    xxmi_mesh_map = {}
    for section_name, draws_list in static_draws.items():
        for comment, mesh_name, drawindexed_value in draws_list:
            xxmi_mesh_map[mesh_name] = drawindexed_value
    
    # Simple label-based replacement using XXMI data
    # Mesh labels are identified by adjacency: a comment immediately followed by drawindexed =
    new_ini_content = []
    last_comment_text = None
    last_comment_line_index = None
    found_any_label = False
    updated_count = 0
    labeled_meshes_in_ini = set()

    for i, line in enumerate(ini_content):
        stripped = line.strip()

        # Track all comments as potential mesh labels
        if stripped.startswith(';'):
            comment = stripped.lstrip(';').strip()
            if comment:
                last_comment_text = stripped
                last_comment_line_index = i
            new_ini_content.append(line)
            continue

        # Check if this drawindexed line follows a comment (adjacency-based detection)
        if stripped.lower().startswith('drawindexed ='):
            # Only count as a valid mesh label if comment was immediately before this line
            if last_comment_line_index == i - 1 and last_comment_text:
                found_any_label = True
                mesh_name = extract_mesh_name_from_comment(last_comment_text)
                labeled_meshes_in_ini.add(mesh_name)

                # Try to update the drawindexed value from XXMI data
                if mesh_name in xxmi_mesh_map:
                    new_val = xxmi_mesh_map[mesh_name]
                    indent = line[:line.index('drawindexed')]
                    line = f"{indent}drawindexed = {new_val}\n"
                    updated_count += 1

            last_comment_text = None
            last_comment_line_index = None
            new_ini_content.append(line)
            continue

        new_ini_content.append(line)

    # Check for issues
    if found_any_label and updated_count == 0:
        report_func({'WARNING'}, "No matching meshes found for update. The file structure didn't change.")
    elif not found_any_label:
        report_func({'ERROR'}, "No labeled drawindexed entries found. Cannot update existing INI without labels.")
        return {'CANCELLED'}

    # Find new meshes in XXMI that aren't labeled in INI (for UI list)
    # Accept any new mesh, but exclude container meshes that were intentionally removed
    new_meshes = []
    
    # Get container mesh names from Blender scene
    container_mesh_names = set()
    containers_collection = bpy.data.collections.get(CONTAINERS_COLLECTION)
    if containers_collection:
        for obj in containers_collection.objects:
            if obj.type == 'MESH':
                container_mesh_names.add(obj.name)
    
    for mesh_name, drawindexed_value in xxmi_mesh_map.items():
        if mesh_name not in labeled_meshes_in_ini:
            # Skip container meshes that were intentionally removed from INI
            if mesh_name in container_mesh_names:
                continue
                
            # Accept any other new mesh from XXMI export
            new_meshes.append({
                'mesh_name': mesh_name,
                'drawindexed_line': drawindexed_value
            })

    # Find deleted meshes (in INI but not in XXMI export)
    deleted_meshes = []
    for mesh_name in labeled_meshes_in_ini:
        if mesh_name not in xxmi_mesh_map:
            deleted_meshes.append({'mesh_name': mesh_name})

    # Handle XXMI export merging for draw= lines (optional feature)
    exported_draws = parse_draw_lines(exported_lines)
    new_ini_content = merge_draw_lines_into_content(exported_draws, new_ini_content)

    # Synchronize override_vertex_count with updated draw values
    draw_values = collect_blend_draw_values(new_ini_content)
    new_ini_content = update_override_vertex_counts(new_ini_content, draw_values)

    # Copy extra files if requested
    if scene.copy_files:
        copy_extra_files(ini_filepath, report_func)
    
    # Write result
    with open(ini_filepath, 'w', encoding='utf-8') as f:
        f.writelines(new_ini_content)
    
    report_func({'INFO'}, f"INI file updated successfully. {updated_count} drawindexed values updated.")
    return {
        'result': {'FINISHED'},
        'new_meshes': new_meshes,
        'deleted_meshes': deleted_meshes
    }


